# general settings
name: Defocus-Deblur-DCE
model_type: MultiHeadImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: defocus-deblur-train
    type: PairedImageDataset
    dataroot_gt: ./datasets/Defocus_Deblurring/train/DPDD/target_crops
    dataroot_lq: ./datasets/Defocus_Deblurring/train/DPDD/inputC_crops 

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

    finetune_augment: false
    
  val:
    name: defocus-deblur-test
    type: PairedImageDataset
    dataroot_gt: ./datasets/Defocus_Deblurring/val/DPDD/target_crops
    dataroot_lq: ./datasets/Defocus_Deblurring/val/DPDD/inputC_crops 
    io_backend:
      type: disk


network_g:
  type: DCENetMHLocal
  width: 60
  enc_blk_nums: [1, 1, 1, 27]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
  n_heads: 4
  combinate_heads: true
  dual_pixel_task: false
  test_cross_blur: false

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: MultiHeadPSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr_mh
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim_mh
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 2345
